/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as V1LinearCallbackRouteImport } from './routes/v1.linear.callback'
import { Route as V1GithubCallbackRouteImport } from './routes/v1.github.callback'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const V1LinearCallbackRoute = V1LinearCallbackRouteImport.update({
  id: '/v1/linear/callback',
  path: '/v1/linear/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const V1GithubCallbackRoute = V1GithubCallbackRouteImport.update({
  id: '/v1/github/callback',
  path: '/v1/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/v1/github/callback': typeof V1GithubCallbackRoute
  '/v1/linear/callback': typeof V1LinearCallbackRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/v1/github/callback': typeof V1GithubCallbackRoute
  '/v1/linear/callback': typeof V1LinearCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/v1/github/callback': typeof V1GithubCallbackRoute
  '/v1/linear/callback': typeof V1LinearCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/settings'
    | '/v1/github/callback'
    | '/v1/linear/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/settings'
    | '/'
    | '/v1/github/callback'
    | '/v1/linear/callback'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/settings'
    | '/_chat/'
    | '/v1/github/callback'
    | '/v1/linear/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  V1GithubCallbackRoute: typeof V1GithubCallbackRoute
  V1LinearCallbackRoute: typeof V1LinearCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/v1/linear/callback': {
      id: '/v1/linear/callback'
      path: '/v1/linear/callback'
      fullPath: '/v1/linear/callback'
      preLoaderRoute: typeof V1LinearCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/github/callback': {
      id: '/v1/github/callback'
      path: '/v1/github/callback'
      fullPath: '/v1/github/callback'
      preLoaderRoute: typeof V1GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  V1GithubCallbackRoute: V1GithubCallbackRoute,
  V1LinearCallbackRoute: V1LinearCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
